# Generated by Django 5.0.1 on 2024-01-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
