# Generated by Django 5.0.1 on 2024-01-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superb', '0003_product_stock_alter_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
